import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../study_group/domain/entities/study_group.dart';
import '../../../study_group/domain/repositories/study_group_repository.dart';
import '../../../study_group/domain/entities/chat_message.dart';
import '../../../study_group/domain/repositories/chat_repository.dart';
import '../../domain/entities/event_model.dart';

class ShareEventDialog extends StatefulWidget {
  final Event event;

  const ShareEventDialog({
    super.key,
    required this.event,
  });

  @override
  State<ShareEventDialog> createState() => _ShareEventDialogState();
}

class _ShareEventDialogState extends State<ShareEventDialog> {
  List<StudyGroup> _myGroups = [];
  bool _isLoading = true;
  String? _selectedGroupId;

  @override
  void initState() {
    super.initState();
    _loadMyGroups();
  }

  Future<void> _loadMyGroups() async {
    try {
      final currentUserId = FirebaseAuth.instance.currentUser?.uid;
      if (currentUserId == null) return;

      final repository = GetIt.instance<StudyGroupRepository>();
      final stream = repository.getUserStudyGroups(currentUserId);
      
      await for (final result in stream.take(1)) {
        result.fold(
          (error) {
            print('Error loading groups: $error');
            setState(() {
              _isLoading = false;
            });
          },
          (groups) {
            setState(() {
              _myGroups = groups;
              _isLoading = false;
            });
          },
        );
        break;
      }
    } catch (e) {
      print('Exception loading groups: $e');
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _shareToGroup() async {
    if (_selectedGroupId == null) return;

    try {
      final currentUserId = FirebaseAuth.instance.currentUser?.uid;
      if (currentUserId == null) return;

      // Create shared event message
      final chatRepository = GetIt.instance<ChatRepository>();
      final message = ChatMessage(
        id: '', // Will be generated by Firebase
        groupId: _selectedGroupId!,
        senderId: currentUserId,
        senderName: FirebaseAuth.instance.currentUser?.displayName ?? 'ผู้ใช้',
        text: 'แชร์กิจกรรม: ${widget.event.title}',
        timestamp: DateTime.now(),
        messageType: MessageType.event,
        eventData: {
          'eventId': widget.event.id,
          'title': widget.event.title,
          'description': widget.event.description,
          'imageUrl': widget.event.imageUrl,
          'date': widget.event.date.toIso8601String(),
          'location': widget.event.location,
        },
      );

      final result = await chatRepository.sendMessage(_selectedGroupId!, message);
      
      result.fold(
        (error) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text('เกิดข้อผิดพลาด: $error'),
                backgroundColor: Colors.red,
              ),
            );
          }
        },
        (_) {
          if (mounted) {
            Navigator.of(context).pop();
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('แชร์กิจกรรมสำเร็จ'),
                backgroundColor: Colors.green,
              ),
            );
          }
        },
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('เกิดข้อผิดพลาด: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
      ),
      child: Container(
        width: double.maxFinite,
        constraints: const BoxConstraints(maxHeight: 500),
        padding: const EdgeInsets.all(20),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Header
            Row(
              children: [
                const Icon(Icons.share, color: Colors.blue),
                const SizedBox(width: 8),
                const Text(
                  'แชร์กิจกรรม',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const Spacer(),
                IconButton(
                  onPressed: () => Navigator.of(context).pop(),
                  icon: const Icon(Icons.close),
                ),
              ],
            ),
            
            const Divider(),
            
            // Event Preview
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.grey[100],
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                children: [
                  // Event Image
                  Container(
                    width: 50,
                    height: 50,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(8),
                      color: Colors.grey[300],
                    ),
                    child: widget.event.imageUrl != null
                        ? ClipRRect(
                            borderRadius: BorderRadius.circular(8),
                            child: Image.network(
                              widget.event.imageUrl!,
                              fit: BoxFit.cover,
                              errorBuilder: (context, error, stackTrace) =>
                                  const Icon(Icons.event, color: Colors.grey),
                            ),
                          )
                        : const Icon(Icons.event, color: Colors.grey),
                  ),
                  const SizedBox(width: 12),
                  // Event Info
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          widget.event.title,
                          style: const TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 14,
                          ),
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                        ),
                        const SizedBox(height: 4),
                        Text(
                          '📅 ${_formatDate(widget.event.date)}',
                          style: TextStyle(
                            color: Colors.grey[600],
                            fontSize: 12,
                          ),
                        ),
                        Text(
                          '📍 ${widget.event.location}',
                          style: TextStyle(
                            color: Colors.grey[600],
                            fontSize: 12,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            
            const SizedBox(height: 16),
            
            // Groups Selection
            const Align(
              alignment: Alignment.centerLeft,
              child: Text(
                'เลือกกลุ่มแชร์',
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                  fontSize: 16,
                ),
              ),
            ),
            
            const SizedBox(height: 8),
            
            // Groups List
            Flexible(
              child: _isLoading
                  ? const Center(child: CircularProgressIndicator())
                  : _myGroups.isEmpty
                      ? const Center(
                          child: Text(
                            'คุณยังไม่ได้เข้าร่วมกลุ่มใดๆ',
                            style: TextStyle(color: Colors.grey),
                          ),
                        )
                      : ListView.builder(
                          shrinkWrap: true,
                          itemCount: _myGroups.length,
                          itemBuilder: (context, index) {
                            final group = _myGroups[index];
                            final isSelected = _selectedGroupId == group.id;
                            
                            return Card(
                              elevation: isSelected ? 4 : 1,
                              color: isSelected ? Colors.blue[50] : null,
                              child: ListTile(
                                leading: CircleAvatar(
                                  backgroundColor: Colors.blue,
                                  child: Text(
                                    group.name.substring(0, 1).toUpperCase(),
                                    style: const TextStyle(
                                      color: Colors.white,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                                title: Text(group.name),
                                subtitle: Text('${group.memberIds?.length ?? 0} สมาชิก'),
                                trailing: isSelected
                                    ? const Icon(Icons.check_circle, color: Colors.blue)
                                    : null,
                                onTap: () {
                                  setState(() {
                                    _selectedGroupId = isSelected ? null : group.id;
                                  });
                                },
                              ),
                            );
                          },
                        ),
            ),
            
            const SizedBox(height: 16),
            
            // Action Buttons
            Row(
              children: [
                Expanded(
                  child: TextButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('ยกเลิก'),
                  ),
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: ElevatedButton.icon(
                    onPressed: _selectedGroupId != null ? _shareToGroup : null,
                    icon: const Icon(Icons.send),
                    label: const Text('แชร์'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.blue,
                      foregroundColor: Colors.white,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  String _formatDate(DateTime date) {
    const monthNames = [
      'ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.',
      'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'
    ];
    
    return '${date.day} ${monthNames[date.month - 1]} ${date.year + 543}';
  }
}
